version: '3.8'

services:
  db:
    image: postgres:15
    container_name: ft_postgres
    restart: always
    environment:
      POSTGRES_DB: familytree
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: ft_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data: