# Generated by Django 6.0.6 on 2026-06-24 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('privacy', models.CharField(choices=[('private', 'Закрытое'), ('link', 'По ссылке'), ('public', 'Открытое')], default='private', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('content_type', models.CharField(max_length=50)),
                ('object_id', models.IntegerField()),
                ('changes', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='trees.familytree')),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('role', models.CharField(choices=[('owner', 'Владелец'), ('editor', 'Редактор'), ('reader', 'Читатель')], max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trees.familytree')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('patronymic', models.CharField(blank=True, max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('death_date', models.DateField(blank=True, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='persons/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='trees.familytree')),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('parent', 'Родитель'), ('child', 'Ребёнок'), ('spouse', 'Супруг'), ('sibling', 'Брат/Сестра')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing', to='trees.person')),
                ('person_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming', to='trees.person')),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='trees.familytree')),
            ],
        ),
        migrations.AddIndex(
            model_name='familytree',
            index=models.Index(fields=['owner', 'created_at'], name='trees_famil_owner_i_e5f10c_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['tree', 'created_at'], name='trees_audit_tree_id_a10711_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['tree', 'created_at'], name='trees_perso_tree_id_353b05_idx'),
        ),
        migrations.AddIndex(
            model_name='relationship',
            index=models.Index(fields=['tree', 'person_from'], name='trees_relat_tree_id_b91dc4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='relationship',
            unique_together={('person_from', 'person_to', 'relationship_type')},
        ),
    ]
