# Generated by Django 6.0.6 on 2026-07-01 07:09

import trees.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0003_person_extra_data_lifeevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='familytree',
            name='share_token',
            field=models.CharField(default=trees.models.generate_share_token, editable=False, max_length=64, unique=True),
        ),
    ]
