# Generated by Django 6.0.6 on 2026-07-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0006_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1),
        ),
    ]
